# Dockerfile.frontend
FROM node:22

WORKDIR /app

RUN corepack enable && corepack prepare yarn@3.6.1 --activate
COPY frontend/package.json frontend/yarn.lock ./
COPY frontend/.yarnrc.yml ./
COPY frontend/.yarn/ .yarn/
RUN yarn install
COPY frontend/ .
RUN yarn build && cp -r /app/out/* /app/frontend/out/

CMD ["node", "watch-build.js"]
