version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    volumes:
      - ./admin:/app
      - ./frontend/content/blog:/app/frontend/content/blog
      - ./admin/static:/app/staticfiles
    environment:
      - DJANGO_STATIC_ROOT=/usr/share/nginx/static
      - PYTHONPATH=/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - ./frontend/content/blog:/app/content/blog  # <-- Share blog posts with Next.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development  # or production for prod
      - BLOG_CONTENT_DIR=/app/content/blog
    env_file:
      - .env
    command: yarn dev  # For dev; for prod, use 'yarn build && yarn start'

  ai:
    build:
      context: ./modules/ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./modules/ai:/app
      - ./frontend/content/blog:/app/frontend/content/blog
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

  static:
    image: nginx:alpine
    container_name: static_site
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./admin/static:/usr/share/nginx/static:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
